run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck

linters-settings:
  errcheck:
    # These are safe to ignore in test files
    exclude-functions:
      - (*testing.T).Log
      - (*testing.T).Logf
      - (*testing.T).Error
      - (*testing.T).Errorf
  staticcheck:
    checks:
      - all
      - "-SA1029" # Context key type - too strict for test files
      - "-SA4023" # Comparison never true - Azure SDK patterns
      - "-SA5011" # Nil pointer - has proper nil handling
      - "-SA9003" # Empty branch - intentional

issues:
  exclude-rules:
    # Exclude unused field mu (used for synchronization)
    - text: "field `mu` is unused"
      linters:
        - unused
    
    # Exclude remaining errcheck in test files
    - path: _test\.go
      linters:
        - errcheck
    
    # Exclude unused in test files  
    - path: _test\.go
      linters:
        - unused
